# Generated by Django 5.2.7 on 2025-11-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='descripicion',
            new_name='description',
        ),
    ]
